# Project: DataStruct
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o 01HelloWorld.o
LINKOBJ  = main.o 01HelloWorld.o
LIBS     = -L"D:/IDE--devc/Dev-Cpp/MinGW64/lib" -L"D:/IDE--devc/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"D:/IDE--devc/Dev-Cpp/MinGW64/include" -I"D:/IDE--devc/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/IDE--devc/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"D:/IDE--devc/Dev-Cpp/MinGW64/include" -I"D:/IDE--devc/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/IDE--devc/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"D:/IDE--devc/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = DataStruct.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.c
	$(CC) -c main.c -o main.o $(CFLAGS)

01HelloWorld.o: 01HelloWorld.c
	$(CC) -c 01HelloWorld.c -o 01HelloWorld.o $(CFLAGS)
