<?xml version="1.0" encoding="utf-8"?><Database Name="MyPet" Class="DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(LocalDB)\v11.0;AttachDbFilename=|DataDirectory|\MyPet.mdf;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="MyPetConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.PetInfo" Member="PetInfo">
    <Type Name="PetInfo">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="kind" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="age" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="name" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="healthStat" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="sex" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="img" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>